### ISSUE TITLE
2.1.3. Implement Iris code data structures supporting different resolutions, dynamic and static masking

### ISSUE THREAD

**Issue by teor2345** [Inversed-Tech/eyelid#62]
This is deliverable 3 in milestone 1 of phase 2.

Iris code data structure abstraction:
- [x] #81
- [x] #84

Iris code encoding methods that can support dynamic and 50% static masking for medium and high resolution iris codes:
Dynamic Masking:
- [x] Generate masked iris code encoding
- [x] Generate mask-only encoding

Static Masking (in `encoded`):
- [ ] Compute maximum overlap between two mask arrays, i.e. a static mask and a measured dynamic mask
- [ ] Generate masked iris code encoding for static mask, with pre-alignment as described [below](https://github.com/Inversed-Tech/eyelid/issues/62#issuecomment-2148136586)
- [ ] Generate unmasked iris code encoding
- [ ] Ensure encoding methods support generic resolutions specified with the `IrisConf` trait

**Comment by bgillesp** [comment]
Following up on a question from @teor2345:
> What's needed for dynamic and static masking?

Dynamic masking is the default operation mode for the current implementation: iris codes are represented as a "masked iris code" encoding plus a somewhat redundant "mask only" encoding; the iris code encoding has coefficients "1 for unmasked 0-bit, -1 for unmasked 1-bit, 0 for masked bit", and the mask encoding has coefficients "1 for unmasked bit, 0 for masked bit".

For static masking, a "query" encoding is like the dynamic masked iris code encoding, but a fixed global static mask is used.  This static mask is chosen to represent the most reliable iris code bits on average, as measured over a reference dataset.  For this encoding, the iris code is aligned prior to encoding so that the _measured_ mask has maximal overlap with the static mask, and then is encoded as a masked iris code, but using the static mask.  Separately, a "database" encoding omits mask data entirely, using coefficients "1 for 0-bit" and "-1 for 1-bit" without regard to any measured or static mask.  Here only one encoding is needed for each query and database entry, in contrast with the two separate "iris code" and "mask" encodings needed for the dynamic mask computations.

(Design note for future reference: the advantage of encoding the static mask in the query rather than the database entry is that this allows easy revisions to the chosen static mask and alignment protocol without having to update the database.)

So the main computational steps needed to support static masking are the following:
- Given two mask arrays (i.e. a measured mask and a static mask), find the cyclic row rotation of the first mask which results in the maximum overlap of mask bits between the two.  Include parameters to specify the range of allowable rotations in the search.
- Encode an iris code input using a static mask:
  - Find the cyclic rotation producing the greatest overlap between the static mask and the measured dynamic mask of the iris code, as above
  - Rotate the input iris code by this optimal rotation
  - Encode the iris code as in a dynamic encoding, but using the static mask as the mask array
- Encode an iris code input with *no* mask, as described above

I'll extend the main task list for this issue to reflect these specifics.

**Comment by teor2345** [comment]
We opened a ticket for static masking only
