### ISSUE TITLE
Lift polynomials over finite fields to polynomials over big numbers. 

### ISSUE THREAD

**Issue by emmorais** [Inversed-Tech/eyelid#94]
As part of homomorphic multiplication algorithm, we need to lift polynomials whose coefficients are taken modulo a prime q, to polynomials over the integers, such that we can do a few operations there, and then convert back to the arithmetic modulo q. 

A simple solution is to use another prime that is big enough (no coefficient actually needs to be reduced after the operations). In particular, we could do something like: 

```
// Sage commands:
// size_q = 79
// size_n = 11
// size = 2*size_q + size_n + 1
// q = random_prime(2**(2*79 + 11 + 1))
// ff = GF(q)
// ff.multiplicative_generator()
// 10
#[derive(MontConfig)]
#[modulus = "292599365471450699889605790713940231423010469055097"]
#[generator = "10"]
pub struct Fq79bnConfig;
pub type Fq79bn = Fp128<MontBackend<Fq79bnConfig, 3>>;
```

- [ ] Create a new Fq79bn that is big enough.
- [ ] Implement a function to convert from Poly over Fq79 to Poly over Fq79bn (no reduction needed).
- [ ] Implement a function to convert back, after reducing modulo q.

On the other hand, this solution is specific to 79 bits. If there is solution to convert from and to big numbers, then even better.

**Comment by teor2345** [comment]
> If there is solution to convert from and to big numbers, then even better.

I don't think there's a generic way of creating a new modular integer type, or having a polynomial with big numbers. I tried a few times, and it's pretty tricky to re-implement the `PrimeField` trait ourselves.

> Implement a function to convert from Poly over Fq79 to Poly over Fq79bn (no reduction needed).
> Implement a function to convert back, after reducing modulo q.

These functions can be generic though, via conversion to `BigUint`.
And we can put the `MUL_NUM` type in the config trait, so that will be generic as well.

So the only thing we'd need to do manually for each polynomial scheme is the `#[derive(MontConfig)]`, modulus & generator calculations, and number of u64 limbs.
